spring:
  application:
    name: order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s #15초 간의 우아한 종료기간을 정의
  r2dbc:
    username: root
    password: 70sungil
    url: r2dbc:mariadb://192.168.1.11:53306/polardb_order
    pool:
      max-create-connection-time: 2s #풀에서 연결객체 하나를 얻을 때까지 기다릴 수 있는 최대한의 시간
      initial-size: 5 #연결 풀의 초기 크기
      max-size: 10 # 풀이 최대한으로 가질수 있는 연력의 수
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:mariadb://192.168.1.11:53306/polardb_order
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 9002
  shutdown: graceful #우아한 종료를 활성화 한다
  netty:
    connection-timeout: 2s #서버와 TCP 연결을 수립하기 위해 기다리는 시간
    idle-timeout: 15s #데이터가 전송되지 않는 경우 TCP 연결을 닫기 전에 기다리는 시간

logging:
  level:
    org:
      springframework:
        r2dbc:
          core:
            DefaultDatabaseClient: debug

#카탈로그 서비스 URL 설정
polar:
  catalog-service-url: "http://172.27.99.163:9091"
